fix(bin/leanpkg): prompt install coreutils on OS X
If cannot find `realpath`, prompt to install coreutils on OS X, otherwise fallback to `readlink -f` (if an old version of coreutils is installed).

diff --git a/bin/leanpkg b/bin/leanpkg
--- a/bin/leanpkg
+++ b/bin/leanpkg
@@ -1,6 +1,17 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
-REALPATH=realpath
+if command -v realpath >/dev/null 2>&1; then
+     REALPATH=realpath
+else
+     unamestr=`uname`
+     # OS X
+     if [[ "$unamestr" == 'Darwin' ]]; then
+         echo "Cannot find 'realpath' command, please install 'realpath'. If you use 'brew', you can install 'greadlink' using 'brew install coreutils'"
+         exit 1
+     else
+         REALPATH="readlink -f"
+     fi
+fi
 
 leandir=$(dirname "$($REALPATH "$0")")/..
 leandir=$($REALPATH "$leandir")
